CREATE DATABASE CLOTHYDB;

CREATE TABLE items (
	id SERIAL PRIMARY KEY,
	name VARCHAR(25) NOT NULL,
	description VARCHAR(100) NOT NULL,
	price SMALLINT NOT NULL,
	img_url VARCHAR NOT NULL,
	available BOOLEAN DEFAULT TRUE
)